// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Schedule.API.Models.Infrastructures;

namespace Sajin_Web.Migrations
{
    [DbContext(typeof(ScheduleDBContext))]
    partial class ScheduleDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Sajin_Web.API.Models.User", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AvaPic");

                    b.Property<Guid?>("EventID");

                    b.Property<string>("Name");

                    b.Property<Guid?>("NoteId");

                    b.Property<string>("PassWord");

                    b.HasKey("UserId");

                    b.HasIndex("EventID");

                    b.HasIndex("NoteId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Schedule.API.Models.Event", b =>
                {
                    b.Property<Guid>("EventID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("Date");

                    b.Property<string>("Description");

                    b.Property<string>("EventName");

                    b.HasKey("EventID");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("Schedule.API.Models.Note", b =>
                {
                    b.Property<Guid>("NoteId")
                        .ValueGeneratedOnAdd();

                    b.Property<Guid?>("EventID");

                    b.HasKey("NoteId");

                    b.HasIndex("EventID");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("Sajin_Web.API.Models.User", b =>
                {
                    b.HasOne("Schedule.API.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventID");

                    b.HasOne("Schedule.API.Models.Note", "Note")
                        .WithMany()
                        .HasForeignKey("NoteId");
                });

            modelBuilder.Entity("Schedule.API.Models.Note", b =>
                {
                    b.HasOne("Schedule.API.Models.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventID");
                });
#pragma warning restore 612, 618
        }
    }
}
